-- ============================================================================
-- AI Gym Routine Scheduler — Supabase schema (generated by gen-sql.mjs)
-- Single-user. Run this once in the Supabase SQL editor.
--
-- Tables (§16 of the spec):
--   profile        one row, the locked user profile + program settings
--   cycle          one row, the 1..4 rotating-split counter
--   exercises      the growable movement library
--   logs           set-level training history (incl. seeded baseline)
--   measurements   §13 progress tracking (bodyweight / body fat %)
--   prescriptions  cached daily plan (engine or Claude), for fast reloads
--
-- NOTE ON ACCESS: tables are created with Row Level Security DISABLED, so the
-- project's anon key can read/write them. That is intentional for a private
-- single-user app and keeps setup friction near zero. Keep your project URL
-- and anon key reasonably private. The README explains an optional passphrase
-- lock-down if you want it.
-- ============================================================================

create extension if not exists pgcrypto;  -- for gen_random_uuid()

-- ---------------------------------------------------------------- profile --
create table if not exists profile (
  id                 text primary key default 'me',
  training_age       text,
  body_comp_goal     text,
  equipment_access   text,
  injuries           text,
  known_limiter      text,
  nutrition_context  text,
  units              text default 'kg',
  weekday_cap_min    int,
  weekend_cap_min    int,
  cardio_cap_min     int,
  reentry_days       int  default 14,
  program_start      date,
  machine_increments jsonb default '{}'::jsonb,
  updated_at         timestamptz default now()
);

-- ------------------------------------------------------------------ cycle --
create table if not exists cycle (
  id         text primary key default 'me',
  week       int  not null default 1 check (week between 1 and 4),
  updated_at timestamptz default now()
);

-- -------------------------------------------------------------- exercises --
create table if not exists exercises (
  name               text primary key,
  type               text,
  primary_muscle     text,
  secondary_muscles  jsonb default '[]'::jsonb,
  equipment          text,
  increment          numeric,
  roles              jsonb default '[]'::jsonb,
  sessions           jsonb default '[]'::jsonb,
  lateral_delt       boolean default false,
  vtaper             boolean default false,
  grip_limited       boolean default false,
  rest_low           int,
  rest_high          int,
  alts               jsonb default '[]'::jsonb,
  data_source        text default 'seeded',
  created_at         timestamptz default now()
);

-- ------------------------------------------------------------------- logs --
create table if not exists logs (
  id            uuid primary key default gen_random_uuid(),
  exercise      text not null,
  weight        numeric,
  reps          int,
  rpe           numeric,
  notes         text default '',
  date          date not null,
  session_type  text,
  week_of_cycle int,
  data_source   text default 'logged',
  created_at    timestamptz default now()
);
create index if not exists logs_exercise_idx on logs (exercise);
create index if not exists logs_date_idx     on logs (date);

-- ----------------------------------------------------------- measurements --
create table if not exists measurements (
  id           uuid primary key default gen_random_uuid(),
  date         date not null,
  bodyweight_kg numeric,
  bodyfat_pct  numeric,
  -- legacy columns, no longer written by the app (kept so old rows still load):
  waist_cm     numeric,
  shoulder_cm  numeric,
  notes        text default '',
  created_at   timestamptz default now()
);
create index if not exists measurements_date_idx on measurements (date);

-- Migration for an EXISTING synced database (safe to run repeatedly):
alter table measurements add column if not exists bodyfat_pct numeric;

-- ---------------------------------------------------------- prescriptions --
create table if not exists prescriptions (
  id           uuid primary key default gen_random_uuid(),
  date         date not null,
  session_key  text,
  payload      jsonb not null,
  source       text default 'engine',
  created_at   timestamptz default now()
);
create index if not exists prescriptions_date_idx on prescriptions (date);

-- ============================ seed: profile =================================
insert into profile (id, training_age, body_comp_goal, equipment_access,
  injuries, known_limiter, nutrition_context, units, weekday_cap_min,
  weekend_cap_min, cardio_cap_min, reentry_days, program_start)
values ('me', 'Intermediate (1–3 years)', 'Skinny-fat correction — V-taper hypertrophy + progressive ab training', 'Full commercial gym',
  'None reported', 'Grip/forearm fatigue on vertical pulling (§8 fail-safe, not an injury)', 'Maintenance / slight deficit — moderate recovery capacity', 'kg',
  60, 90, 30,
  14, '2025-06-30')
on conflict (id) do nothing;

-- ============================= seed: cycle ==================================
insert into cycle (id, week) values ('me', 1)
on conflict (id) do nothing;

-- =========================== seed: exercises ================================
insert into exercises (name, type, primary_muscle, secondary_muscles, equipment,
  increment, roles, sessions, lateral_delt, vtaper, grip_limited, rest_low,
  rest_high, alts, data_source) values
  ('Bench Press (Dumbbell)', 'compound', 'chest', '["triceps","front delt"]'::jsonb, 'dumbbell', 2.5, '["chest_press","chest_flat"]'::jsonb, '["backchest","push"]'::jsonb, false, false, false, 120, 180, '["Barbell Bench Press","Machine Chest Press"]'::jsonb, 'seeded'),
  ('Barbell Bench Press', 'compound', 'chest', '["triceps","front delt"]'::jsonb, 'barbell', 5, '["chest_press","chest_flat"]'::jsonb, '["backchest","push"]'::jsonb, false, false, false, 120, 180, '["Bench Press (Dumbbell)","Machine Chest Press"]'::jsonb, 'seeded'),
  ('Machine Chest Press', 'compound', 'chest', '["triceps"]'::jsonb, 'machine', null, '["chest_press","chest_flat"]'::jsonb, '["backchest","push"]'::jsonb, false, false, false, 120, 180, '["Barbell Bench Press","Bench Press (Dumbbell)"]'::jsonb, 'seeded'),
  ('Incline Bench Press (Smith Machine)', 'compound', 'upper chest', '["front delt","triceps"]'::jsonb, 'machine', 5, '["chest_press","chest_incline"]'::jsonb, '["backchest","push"]'::jsonb, false, true, false, 120, 180, '["Incline Barbell Press","Incline Dumbbell Bench Press"]'::jsonb, 'seeded'),
  ('Incline Dumbbell Bench Press', 'compound', 'upper chest', '["front delt","triceps"]'::jsonb, 'dumbbell', 2.5, '["chest_press","chest_incline"]'::jsonb, '["backchest","push"]'::jsonb, false, true, false, 120, 180, '["Incline Barbell Press","Incline Bench Press (Smith Machine)"]'::jsonb, 'seeded'),
  ('Incline Barbell Press', 'compound', 'upper chest', '["front delt","triceps"]'::jsonb, 'barbell', 5, '["chest_press","chest_incline"]'::jsonb, '["backchest","push"]'::jsonb, false, true, false, 120, 180, '["Incline Bench Press (Smith Machine)","Incline Dumbbell Bench Press"]'::jsonb, 'seeded'),
  ('Decline Dumbbell Bench Press', 'compound', 'chest', '["triceps"]'::jsonb, 'dumbbell', 2.5, '["chest_press","chest_flat"]'::jsonb, '["push","backchest"]'::jsonb, false, false, false, 120, 180, '["Bench Press (Dumbbell)","Machine Chest Press"]'::jsonb, 'seeded'),
  ('Cable Fly Crossovers', 'isolation', 'chest', '[]'::jsonb, 'cable', null, '["chest_iso"]'::jsonb, '["push","backchest"]'::jsonb, false, false, false, 60, 90, '["Pec Deck Machine Flyes","Incline Dumbbell Flyes"]'::jsonb, 'seeded'),
  ('Pec Deck Machine Flyes', 'isolation', 'chest', '[]'::jsonb, 'machine', null, '["chest_iso"]'::jsonb, '["push","backchest"]'::jsonb, false, false, false, 60, 90, '["Cable Fly Crossovers","Incline Dumbbell Flyes"]'::jsonb, 'seeded'),
  ('Incline Dumbbell Flyes', 'isolation', 'upper chest', '[]'::jsonb, 'dumbbell', 2.5, '["chest_iso"]'::jsonb, '["push","backchest"]'::jsonb, false, true, false, 60, 90, '["Cable Fly Crossovers","Pec Deck Machine Flyes"]'::jsonb, 'seeded'),
  ('Low-to-High Cable Fly', 'isolation', 'upper chest', '[]'::jsonb, 'cable', null, '["chest_iso"]'::jsonb, '["push","backchest"]'::jsonb, false, true, false, 60, 90, '["Incline Dumbbell Flyes","Cable Fly Crossovers"]'::jsonb, 'seeded'),
  ('Weighted Dips', 'compound', 'chest', '["triceps"]'::jsonb, 'bodyweight', 2.5, '["chest_press","chest_flat","triceps_iso"]'::jsonb, '["push","backchest"]'::jsonb, false, false, false, 120, 180, '["Machine Chest Press","Close-Grip Bench Press"]'::jsonb, 'seeded'),
  ('Lat Pulldown (Cable)', 'compound', 'lats', '["biceps"]'::jsonb, 'cable', null, '["back_vertical"]'::jsonb, '["pull","backchest"]'::jsonb, false, true, false, 120, 180, '["Neutral-Grip Lat Pulldowns","Pull Up (Assisted)"]'::jsonb, 'seeded'),
  ('Wide-Grip Lat Pulldown', 'compound', 'lats', '["biceps"]'::jsonb, 'cable', null, '["back_vertical"]'::jsonb, '["pull","backchest"]'::jsonb, false, true, false, 120, 180, '["Lat Pulldown (Cable)","Neutral-Grip Lat Pulldowns"]'::jsonb, 'seeded'),
  ('Neutral-Grip Lat Pulldowns', 'compound', 'lats', '["biceps"]'::jsonb, 'cable', null, '["back_vertical"]'::jsonb, '["pull","backchest"]'::jsonb, false, true, false, 120, 180, '["Lat Pulldown (Cable)","Chin-Ups"]'::jsonb, 'seeded'),
  ('Pull Up', 'compound', 'lats', '["biceps"]'::jsonb, 'bodyweight', 2.5, '["back_vertical"]'::jsonb, '["pull","backchest"]'::jsonb, false, true, true, 120, 180, '["Pull Up (Assisted)","Lat Pulldown (Cable)"]'::jsonb, 'seeded'),
  ('Pull Up (Assisted)', 'compound', 'lats', '["biceps"]'::jsonb, 'machine', null, '["back_vertical"]'::jsonb, '["pull","backchest"]'::jsonb, false, true, true, 120, 180, '["Pull Up","Lat Pulldown (Cable)"]'::jsonb, 'seeded'),
  ('Chin-Ups', 'compound', 'lats', '["biceps"]'::jsonb, 'bodyweight', 2.5, '["back_vertical"]'::jsonb, '["pull","backchest"]'::jsonb, false, true, true, 120, 180, '["Pull Up (Assisted)","Lat Pulldown (Cable)"]'::jsonb, 'seeded'),
  ('Inverted Rows', 'compound', 'back', '["biceps","rear delt"]'::jsonb, 'bodyweight', null, '["back_horizontal","back_secondary"]'::jsonb, '["pull","backchest"]'::jsonb, false, false, false, 120, 180, '["Seated Cable Row – V Grip","Chest-Supported Machine Rows"]'::jsonb, 'seeded'),
  ('Bent Over Row (Barbell)', 'compound', 'back', '["biceps","rear delt"]'::jsonb, 'barbell', 5, '["back_horizontal","back_secondary"]'::jsonb, '["pull","backchest"]'::jsonb, false, false, false, 120, 180, '["T-Bar Rows","Dumbbell Rows"]'::jsonb, 'seeded'),
  ('Dumbbell Rows', 'compound', 'back', '["biceps","rear delt"]'::jsonb, 'dumbbell', 2.5, '["back_horizontal","back_secondary"]'::jsonb, '["pull","backchest"]'::jsonb, false, false, false, 120, 180, '["Bent Over Row (Barbell)","T-Bar Rows"]'::jsonb, 'seeded'),
  ('Meadows Rows', 'compound', 'back', '["biceps","rear delt"]'::jsonb, 'barbell', 5, '["back_horizontal","back_secondary"]'::jsonb, '["pull","backchest"]'::jsonb, false, false, false, 120, 180, '["T-Bar Rows","Dumbbell Rows"]'::jsonb, 'seeded'),
  ('T-Bar Rows', 'compound', 'back', '["biceps","rear delt"]'::jsonb, 'machine', 5, '["back_horizontal","back_secondary"]'::jsonb, '["pull","backchest"]'::jsonb, false, false, false, 120, 180, '["Bent Over Row (Barbell)","Meadows Rows"]'::jsonb, 'seeded'),
  ('Seated Cable Row – V Grip', 'compound', 'back', '["biceps","rear delt"]'::jsonb, 'cable', null, '["back_horizontal","back_secondary"]'::jsonb, '["pull","backchest"]'::jsonb, false, false, false, 120, 180, '["Chest-Supported Machine Rows","Inverted Rows"]'::jsonb, 'seeded'),
  ('Chest-Supported Machine Rows', 'compound', 'back', '["rear delt"]'::jsonb, 'machine', null, '["back_horizontal","back_secondary"]'::jsonb, '["pull","backchest"]'::jsonb, false, false, false, 120, 180, '["Seated Cable Row – V Grip","T-Bar Rows"]'::jsonb, 'seeded'),
  ('Straight-Arm Cable Pullovers', 'isolation', 'lats', '[]'::jsonb, 'cable', null, '["back_secondary","lat_iso"]'::jsonb, '["pull","backchest"]'::jsonb, false, true, false, 60, 90, '["Straight-Arm Lat Pulldown","Neutral-Grip Lat Pulldowns"]'::jsonb, 'seeded'),
  ('Straight-Arm Lat Pulldown', 'isolation', 'lats', '[]'::jsonb, 'cable', null, '["lat_iso"]'::jsonb, '["pull","backchest"]'::jsonb, false, true, false, 60, 90, '["Straight-Arm Cable Pullovers","Neutral-Grip Lat Pulldowns"]'::jsonb, 'seeded'),
  ('Lateral Raise (Dumbbell)', 'isolation', 'lateral delt', '[]'::jsonb, 'dumbbell', 2.5, '["lateral_delt"]'::jsonb, '["arms","legs","backchest","push","pull"]'::jsonb, true, true, false, 60, 90, '["Cable Lateral Raises","Machine Lateral Raises"]'::jsonb, 'seeded'),
  ('Cable Lateral Raises', 'isolation', 'lateral delt', '[]'::jsonb, 'cable', null, '["lateral_delt"]'::jsonb, '["arms","legs","backchest","push","pull"]'::jsonb, true, true, false, 60, 90, '["Lateral Raise (Dumbbell)","Machine Lateral Raises"]'::jsonb, 'seeded'),
  ('Machine Lateral Raises', 'isolation', 'lateral delt', '[]'::jsonb, 'machine', null, '["lateral_delt"]'::jsonb, '["arms","legs","backchest","push","pull"]'::jsonb, true, true, false, 60, 90, '["Lateral Raise (Dumbbell)","Cable Lateral Raises"]'::jsonb, 'seeded'),
  ('Face Pulls', 'isolation', 'rear delt', '[]'::jsonb, 'cable', null, '["rear_delt"]'::jsonb, '["push","pull","backchest"]'::jsonb, false, false, false, 60, 90, '["Cable Face Pulls","Rear Delt Reverse Fly (Machine)"]'::jsonb, 'seeded'),
  ('Cable Face Pulls', 'isolation', 'rear delt', '[]'::jsonb, 'cable', null, '["rear_delt"]'::jsonb, '["push","pull","backchest"]'::jsonb, false, false, false, 60, 90, '["Face Pulls","Rear Delt Dumbbell Flyes"]'::jsonb, 'seeded'),
  ('Rear Delt Reverse Fly (Machine)', 'isolation', 'rear delt', '[]'::jsonb, 'machine', null, '["rear_delt"]'::jsonb, '["push","pull","backchest"]'::jsonb, false, false, false, 60, 90, '["Rear Delt Dumbbell Flyes","Cable Face Pulls"]'::jsonb, 'seeded'),
  ('Rear Delt Dumbbell Flyes', 'isolation', 'rear delt', '[]'::jsonb, 'dumbbell', 2.5, '["rear_delt"]'::jsonb, '["push","pull","backchest"]'::jsonb, false, false, false, 60, 90, '["Rear Delt Reverse Fly (Machine)","Cable Face Pulls"]'::jsonb, 'seeded'),
  ('Incline Dumbbell Y-Raises', 'isolation', 'rear delt', '["lower trap"]'::jsonb, 'dumbbell', 2.5, '["rear_delt"]'::jsonb, '["push","pull","backchest"]'::jsonb, false, false, false, 60, 90, '["Face Pulls","Rear Delt Dumbbell Flyes"]'::jsonb, 'seeded'),
  ('Hammer Curl (Dumbbell)', 'isolation', 'biceps', '["forearm"]'::jsonb, 'dumbbell', 2.5, '["biceps_heavy","biceps_iso"]'::jsonb, '["arms","pull"]'::jsonb, false, false, false, 60, 90, '["Concentration Curls","Reverse Cable Curls"]'::jsonb, 'seeded'),
  ('Preacher Curl (Barbell)', 'isolation', 'biceps', '[]'::jsonb, 'barbell', 5, '["biceps_heavy","biceps_iso"]'::jsonb, '["arms","pull"]'::jsonb, false, false, false, 60, 90, '["EZ-Bar Curls","Incline Dumbbell Curls"]'::jsonb, 'seeded'),
  ('Bicep Curl (Cable)', 'isolation', 'biceps', '[]'::jsonb, 'cable', null, '["biceps_iso"]'::jsonb, '["arms","pull"]'::jsonb, false, false, false, 60, 90, '["Dumbbell Bicep Curls","EZ-Bar Curls"]'::jsonb, 'seeded'),
  ('Dumbbell Bicep Curls', 'isolation', 'biceps', '[]'::jsonb, 'dumbbell', 2.5, '["biceps_heavy","biceps_iso"]'::jsonb, '["arms","pull"]'::jsonb, false, false, false, 60, 90, '["Bicep Curl (Cable)","Incline Dumbbell Curls"]'::jsonb, 'seeded'),
  ('Concentration Curls', 'isolation', 'biceps', '[]'::jsonb, 'dumbbell', 2.5, '["biceps_iso"]'::jsonb, '["arms","pull"]'::jsonb, false, false, false, 60, 90, '["Hammer Curl (Dumbbell)","Bicep Curl (Cable)"]'::jsonb, 'seeded'),
  ('Incline Dumbbell Curls', 'isolation', 'biceps', '[]'::jsonb, 'dumbbell', 2.5, '["biceps_iso"]'::jsonb, '["arms","pull"]'::jsonb, false, false, false, 60, 90, '["Dumbbell Bicep Curls","Preacher Curl (Barbell)"]'::jsonb, 'seeded'),
  ('EZ-Bar Curls', 'isolation', 'biceps', '[]'::jsonb, 'barbell', 5, '["biceps_heavy","biceps_iso"]'::jsonb, '["arms","pull"]'::jsonb, false, false, false, 60, 90, '["Preacher Curl (Barbell)","Dumbbell Bicep Curls"]'::jsonb, 'seeded'),
  ('Reverse Cable Curls', 'isolation', 'biceps', '["forearm"]'::jsonb, 'cable', null, '["biceps_iso"]'::jsonb, '["arms","pull"]'::jsonb, false, false, false, 60, 90, '["Hammer Curl (Dumbbell)","Bicep Curl (Cable)"]'::jsonb, 'seeded'),
  ('Triceps Rope Pushdown', 'isolation', 'triceps', '[]'::jsonb, 'cable', null, '["triceps_iso"]'::jsonb, '["arms","push","backchest"]'::jsonb, false, false, false, 60, 90, '["Straight-Bar Cable Pushdowns","Overhead Triceps Extension (Cable)"]'::jsonb, 'seeded'),
  ('Straight-Bar Cable Pushdowns', 'isolation', 'triceps', '[]'::jsonb, 'cable', null, '["triceps_iso"]'::jsonb, '["arms","push"]'::jsonb, false, false, false, 60, 90, '["Triceps Rope Pushdown","Overhead Triceps Extension (Cable)"]'::jsonb, 'seeded'),
  ('Overhead Triceps Extension (Cable)', 'isolation', 'triceps', '[]'::jsonb, 'cable', null, '["triceps_iso"]'::jsonb, '["arms","push"]'::jsonb, false, false, false, 60, 90, '["Overhead Dumbbell Extensions","Triceps Rope Pushdown"]'::jsonb, 'seeded'),
  ('Overhead Dumbbell Extensions', 'isolation', 'triceps', '[]'::jsonb, 'dumbbell', 2.5, '["triceps_iso"]'::jsonb, '["arms","push"]'::jsonb, false, false, false, 60, 90, '["Overhead Triceps Extension (Cable)","EZ-Bar Skull Crushers"]'::jsonb, 'seeded'),
  ('EZ-Bar Skull Crushers', 'isolation', 'triceps', '[]'::jsonb, 'barbell', 5, '["triceps_iso","triceps_heavy"]'::jsonb, '["arms","push"]'::jsonb, false, false, false, 60, 90, '["Overhead Dumbbell Extensions","Close-Grip Bench Press"]'::jsonb, 'seeded'),
  ('Close-Grip Bench Press', 'compound', 'triceps', '["chest"]'::jsonb, 'barbell', 5, '["triceps_iso","triceps_heavy","chest_press"]'::jsonb, '["arms","push","backchest"]'::jsonb, false, false, false, 120, 180, '["EZ-Bar Skull Crushers","Weighted Dips"]'::jsonb, 'seeded'),
  ('Barbell Back Squat', 'compound', 'quads', '["glutes"]'::jsonb, 'barbell', 5, '["lower_compound"]'::jsonb, '["legs"]'::jsonb, false, false, false, 120, 180, '["Hack Squat","Leg Press"]'::jsonb, 'seeded'),
  ('Hack Squat', 'compound', 'quads', '["glutes"]'::jsonb, 'machine', null, '["lower_compound"]'::jsonb, '["legs"]'::jsonb, false, false, false, 120, 180, '["Barbell Back Squat","Leg Press"]'::jsonb, 'seeded'),
  ('Leg Press', 'compound', 'quads', '["glutes"]'::jsonb, 'machine', null, '["lower_compound"]'::jsonb, '["legs"]'::jsonb, false, false, false, 120, 180, '["Hack Squat","Goblet Squat"]'::jsonb, 'seeded'),
  ('Goblet Squat', 'compound', 'quads', '["glutes"]'::jsonb, 'dumbbell', 2.5, '["lower_compound"]'::jsonb, '["legs"]'::jsonb, false, false, false, 120, 180, '["Leg Press","Bulgarian Split Squat"]'::jsonb, 'seeded'),
  ('Bulgarian Split Squat', 'compound', 'quads', '["glutes"]'::jsonb, 'dumbbell', 2.5, '["lower_compound","quad_iso"]'::jsonb, '["legs"]'::jsonb, false, false, false, 120, 180, '["Walking Lunges","Goblet Squat"]'::jsonb, 'seeded'),
  ('Walking Lunges', 'compound', 'quads', '["glutes"]'::jsonb, 'dumbbell', 2.5, '["lower_compound"]'::jsonb, '["legs"]'::jsonb, false, false, false, 120, 180, '["Bulgarian Split Squat","Goblet Squat"]'::jsonb, 'seeded'),
  ('Leg Extensions', 'isolation', 'quads', '[]'::jsonb, 'machine', null, '["quad_iso"]'::jsonb, '["legs"]'::jsonb, false, false, false, 60, 90, '["Hack Squat","Goblet Squat"]'::jsonb, 'seeded'),
  ('Romanian Deadlift (Barbell)', 'compound', 'hamstrings', '["glutes","lower back"]'::jsonb, 'barbell', 5, '["posterior_chain"]'::jsonb, '["legs"]'::jsonb, false, false, false, 120, 180, '["Cable Pull-Throughs","Lying Leg Curls"]'::jsonb, 'seeded'),
  ('Seated Leg Curls', 'isolation', 'hamstrings', '[]'::jsonb, 'machine', null, '["knee_flexion","posterior_chain"]'::jsonb, '["legs"]'::jsonb, false, false, false, 60, 90, '["Lying Leg Curls","Cable Pull-Throughs"]'::jsonb, 'seeded'),
  ('Lying Leg Curls', 'isolation', 'hamstrings', '[]'::jsonb, 'machine', null, '["knee_flexion","posterior_chain"]'::jsonb, '["legs"]'::jsonb, false, false, false, 60, 90, '["Seated Leg Curls","Cable Pull-Throughs"]'::jsonb, 'seeded'),
  ('Cable Pull-Throughs', 'compound', 'hamstrings', '["glutes"]'::jsonb, 'cable', null, '["posterior_chain"]'::jsonb, '["legs"]'::jsonb, false, false, false, 120, 180, '["Romanian Deadlift (Barbell)","Lying Leg Curls"]'::jsonb, 'seeded'),
  ('Hip Thrusts', 'compound', 'glutes', '["hamstrings"]'::jsonb, 'barbell', 5, '["posterior_chain"]'::jsonb, '["legs"]'::jsonb, false, false, false, 120, 180, '["Cable Pull-Throughs","Romanian Deadlift (Barbell)"]'::jsonb, 'seeded'),
  ('Standing Calf Raises', 'isolation', 'calves', '[]'::jsonb, 'machine', null, '["calves"]'::jsonb, '["legs","push","pull"]'::jsonb, false, false, false, 60, 90, '["Seated Calf Raises"]'::jsonb, 'seeded'),
  ('Seated Calf Raises', 'isolation', 'calves', '[]'::jsonb, 'machine', null, '["calves"]'::jsonb, '["legs"]'::jsonb, false, false, false, 60, 90, '["Standing Calf Raises"]'::jsonb, 'seeded'),
  ('Weighted Cable Crunches', 'isolation', 'abs', '[]'::jsonb, 'cable', null, '["ab_flexion"]'::jsonb, '["push","pull"]'::jsonb, false, false, false, 60, 90, '["Machine Ab Crunches","Hanging Leg Raises"]'::jsonb, 'seeded'),
  ('Machine Ab Crunches', 'isolation', 'abs', '[]'::jsonb, 'machine', null, '["ab_flexion"]'::jsonb, '["push","pull"]'::jsonb, false, false, false, 60, 90, '["Weighted Cable Crunches","Hanging Leg Raises"]'::jsonb, 'seeded'),
  ('Hanging Leg Raises', 'isolation', 'lower abs', '[]'::jsonb, 'bodyweight', 2.5, '["ab_lower"]'::jsonb, '["push","pull"]'::jsonb, false, false, false, 60, 90, '["Machine Ab Crunches","Weighted Cable Crunches"]'::jsonb, 'seeded')
on conflict (name) do nothing;

-- ============================= seed: logs ===================================
-- Baseline lifts (§5), dated the day before program start so week-1
-- prescriptions can read them. Weighted Cable Crunch and Hanging Leg Raise are
-- intentionally absent so they trigger the calibration pass on first use.
insert into logs (exercise, weight, reps, rpe, notes, date, session_type,
  week_of_cycle, data_source) values
  ('Bench Press (Dumbbell)', 17.5, 12, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Bench Press (Dumbbell)', 20, 12, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Bench Press (Dumbbell)', 22.5, 8, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Incline Bench Press (Smith Machine)', 50, 12, null, 'Top set inconsistent — 50–55kg working weight', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Incline Bench Press (Smith Machine)', 60, 8, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Incline Bench Press (Smith Machine)', 50, 10, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Cable Fly Crossovers', 10, 12, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Cable Fly Crossovers', 15, 7, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Cable Fly Crossovers', 10, 10, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Triceps Rope Pushdown', 25, 15, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Triceps Rope Pushdown', 30, 12, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Triceps Rope Pushdown', 30, 6, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Rear Delt Reverse Fly (Machine)', 32, 15, 10, 'All sets top of range at RPE10 — ready to increase', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Rear Delt Reverse Fly (Machine)', 32, 15, 10, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Rear Delt Reverse Fly (Machine)', 32, 15, 10, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Lateral Raise (Dumbbell)', 7.5, 10, null, 'Weight inconsistent — standardize to 5–6kg working weight', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Lateral Raise (Dumbbell)', 5, 20, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Lateral Raise (Dumbbell)', 5, 15, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Lateral Raise (Dumbbell)', 5, 15, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Lateral Raise (Dumbbell)', 5, 12, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Overhead Triceps Extension (Cable)', 10, 12, null, 'Single-arm', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Overhead Triceps Extension (Cable)', 10, 10, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Overhead Triceps Extension (Cable)', 5, 12, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Overhead Triceps Extension (Cable)', 5, 10, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Hammer Curl (Dumbbell)', 10, 12, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Hammer Curl (Dumbbell)', 12.5, 7, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Hammer Curl (Dumbbell)', 10, 8, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Preacher Curl (Barbell)', 15, 15, null, 'Hit 15/12/10 vs an 8-rep target — too light, increase', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Preacher Curl (Barbell)', 15, 12, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Preacher Curl (Barbell)', 15, 10, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Pull Up', 0, 5, null, 'Bodyweight — 5 reps', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Pull Up (Assisted)', 20, 12, null, 'Grip/forearm fatigue noted — see grip fail-safe', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Pull Up (Assisted)', 20, 8, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Bent Over Row (Barbell)', 40, 8, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Bent Over Row (Barbell)', 45, 8, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Bent Over Row (Barbell)', 50, 8, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Bent Over Row (Barbell)', 50, 7, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Lat Pulldown (Cable)', 29, 12, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Lat Pulldown (Cable)', 36, 12, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Lat Pulldown (Cable)', 43, 8, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Lat Pulldown (Cable)', 43, 7, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Seated Cable Row – V Grip', 29, 12, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Seated Cable Row – V Grip', 36, 8, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Seated Cable Row – V Grip', 36, 5, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Bicep Curl (Cable)', 20, 12, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Bicep Curl (Cable)', 25, 12, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline'),
  ('Bicep Curl (Cable)', 25, 10, null, '', '2025-06-29', 'baseline', 1, 'user-reported-baseline');

-- ============================ end of schema ================================

-- ============================================================================
-- MIGRATION: set-level ordering, station tracking, session outcome.
-- Safe to run repeatedly.
-- ============================================================================

-- Set order was previously implied by created_at, which breaks when rows sync
-- out of order. Every progression and deload rule now depends on knowing which
-- set is set one, so it is stored explicitly.
alter table logs add column if not exists set_index int;
alter table logs add column if not exists station   text;

-- Backfill from insertion order — correct for existing single-device history.
with ordered as (
  select id, row_number() over (
           partition by date, exercise order by created_at, id
         ) - 1 as ix
  from logs where set_index is null
)
update logs l set set_index = o.ix from ordered o where l.id = o.id;

create index if not exists logs_day_ex_idx on logs (date, exercise, set_index);

-- Sessions were only ever done-or-missing. Distinguish prescribed / substituted
-- / skipped so the plan view can tell you what actually happened.
create table if not exists session_status (
  date          date not null,
  session_key   text not null,
  status        text not null default 'as_prescribed'
                check (status in ('as_prescribed','substituted','skipped','partial')),
  substitutions jsonb default '[]'::jsonb,
  note          text default '',
  updated_at    timestamptz default now(),
  primary key (date, session_key)
);

-- Assist machines counter-weight the lifter: more load = easier. Progression on
-- these must move the number DOWN, so they need their own flag.
alter table exercises add column if not exists inverse_load boolean default false;
update exercises set inverse_load = true where name = 'Pull Up (Assisted)';
